---
- name: Mount network share and clone disk
  hosts: all
  become: yes
  vars:
    network_share: "//10.0.0.150/HDD/backups"
    mount_point: "/mnt/zima/backups"
    share_user: "user"
    share_password: "password"

  tasks:
    - name: Get hostname
      command: hostname
      register: hostname_result

    - name: Set hostname and timestamp variables
      set_fact:
        hostname: "{{ hostname_result.stdout }}"
        timestamp: "{{ ansible_date_time.iso8601 | replace(':', '-') }}"

    - name: Ensure /mnt/zima directory exists
      file:
        path: /mnt/zima
        state: directory
        mode: '0755'
      become: yes

    - name: Ensure mount point directory exists
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'
      become: yes

    - name: Install cifs-utils for mounting CIFS shares
      package:
        name: cifs-utils
        state: present
      become: yes

    - name: Mount network share
      mount:
        path: "{{ mount_point }}"
        src: "{{ network_share }}"
        fstype: cifs
        opts: "username={{ share_user }},password={{ share_password }},uid=0,gid=0"
        state: mounted
      become: yes

    - name: Ensure images directory exists
      file:
        path: "{{ mount_point }}/images"
        state: directory
        mode: '0755'
      become: yes

    - name: Clone disk using dd
      shell: |
        dd if=/dev/sda bs=64K conv=noerror,sync status=progress | 
        gzip -c > "{{ mount_point }}/images/{{ hostname }}_{{ timestamp }}.img.gz"
      register: dd_result
      failed_when: dd_result.rc != 0
      become: yes

    - name: Display dd command output
      debug:
        var: dd_result.stdout_lines

    - name: Unmount network share
      mount:
        path: "{{ mount_point }}"
        state: unmounted
      become: yes
