---
- name: Mount network share and clone disk
  hosts: localhost
  become: yes
  vars:
    network_share: "//10.0.0.150/HDD/backups"
    mount_point: "/mnt/zima/backups"
    share_user: "user"
    share_password: "password"
    hostname: "{{ ansible_hostname }}"
    timestamp: "{{ ansible_date_time.iso8601 | replace(':', '-') }}"

  tasks:
    - name: Ensure mount point directory exists
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'

    - name: Install cifs-utils for mounting CIFS shares
      package:
        name: cifs-utils
        state: present

    - name: Mount network share
      mount:
        path: "{{ mount_point }}"
        src: "{{ network_share }}"
        fstype: cifs
        opts: "username={{ share_user }},password={{ share_password }},uid=0,gid=0"
        state: mounted

    - name: Ensure images directory exists
      file:
        path: "{{ mount_point }}/images"
        state: directory
        mode: '0755'

    - name: Clone disk using dd
      command: >
        dd if=/dev/sda bs=64K conv=noerror,sync status=progress | 
        gzip -c > "{{ mount_point }}/images/{{ hostname }}_{{ timestamp }}.img.gz"
      register: dd_result
      failed_when: dd_result.rc != 0

    - name: Display dd command output
      debug:
        var: dd_result.stdout_lines

    - name: Unmount network share
      mount:
        path: "{{ mount_point }}"
        state: unmounted
