---
- name: Create Ansible user account and set up SSH access
  hosts: all
  become: yes
  vars:
    username: ansible
    password: "{{ 'your_password_here' | password_hash('sha512') }}"
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCVYHN/kEigZtbuFP1L9zc5iWI9dLl5764w7JC9S50KzHiG1PF8V1QDmoY6N1Te5q6TO/fxZ6X94RMGbY/mmQB+2UPie1p4v5LrAElRglGrXzkuWudFtxmirak1WAn0h2dL2K1pVyJsV7Oqbj+vojzTznMYsKOxvInle7mkFWMIfUuJisOXYNHORiynl8Va/ymn0Iv3D2WVfiQeFY//L1ACZpasTv/IFAWbS2cdIdM442kT/XF9Fat3/cCz0yiU2vvJ4MzpMzno7Sdc9zk9CUhsMEx+kgUXQ606Xms2FxtkDlpH8rwg7aip+TFrG5CxE5UZIt3u7YJ41YwGcygcfxEj rsa-key-20240831"

  tasks:
    - name: Ensure group "ansible" exists
      group:
        name: "{{ username }}"
        state: present

    - name: Create the Ansible user
      user:
        name: "{{ username }}"
        group: "{{ username }}"
        groups: sudo
        shell: /bin/bash
        password: "{{ password }}"
        update_password: on_create
        state: present
      register: user_creation

    - name: Create .ssh directory
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
      when: user_creation is changed

    - name: Add SSH key for the Ansible user
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ ssh_key }}"
      register: ssh_key_addition

    - name: Ensure correct permissions on authorized_keys file
      file:
        path: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'
      when: ssh_key_addition is changed

    - name: Allow Ansible user to run sudo without a password
      lineinfile:
        path: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        validate: '/usr/sbin/visudo -cf %s'
      when: user_creation is changed

    - name: Ensure SSH service is running
      service:
        name: sshd
        state: started
        enabled: yes
