---
- name: Create Ansible user account and set up SSH access
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars:
    username: ansible
    group: user
    password: "password"
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCTbLajMy0/JIX8yYqOj9Q7lm/ygFDQGPeCJDdgvNe5Apa+abFofRbqHtvI08B3I9CoHPvqlQsx6g8YokmWaRP5UMWgu4hmuOFXM8guhfUbwKQMuCZMdBdipQY0NaEdKsd2Zk4/NhlO0DGrWCLBypv2XQfw5exVGNirwSttYRAqAkuhiprVD+HFeeTbDY4psxwrdUvx8czuZbDCvtRoOtA+00d3eINPI/A/hAezAbY33qTUfGKC3dAHBHEuvznfwd1GQCgPVAvqEr0L3wiNcghpOhLrGQYM5N6qawpSCv1AlfeME9lQ2SW3jc0/luNOOdpHdfEVxZpbnYldpEGpQuwtEUhbmdEUOUxGA85LUBYzM3EFn+ekHkQzZP99d/+PYOg22UEVMVTsDCOhVflEfHtSR/GDMpawl1XLGxbbHEMZbBbl1n73iZqvD02Pj5TemET7J8xuNN5DpTH2xj8HDZv40flfwDEWDtOuTp5sl94lxbrzmPDTZdMUia8NbtZvb9M= 2/6fQ3FeUXIgdz8IV4to1JknujqOmfulHnwHzURHOgk"

  tasks:
    - name: Ensure we have sudo access
      command: whoami
      become: yes
      changed_when: false
      register: sudo_check
      ignore_errors: yes

    - name: Fail if we don't have sudo access
      fail:
        msg: "The current user does not have sudo access. Please ensure the user has sudo privileges."
      when: sudo_check is failed

    - name: Check if user group exists
      getent:
        database: group
        key: "{{ group }}"
      register: user_group_check

    - name: Fail if user group doesn't exist
      fail:
        msg: "The group '{{ group }}' does not exist on the system."
      when: user_group_check.failed

    - name: Create the Ansible user
      user:
        name: "{{ username }}"
        group: "{{ group }}"
        groups: "sudo,root"
        shell: /bin/bash
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create
        state: present
      register: user_creation

    - name: Create .ssh directory
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ group }}"
        mode: '0700'
      when: user_creation is changed

    - name: Add SSH key for the Ansible user
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ ssh_key }}"
      register: ssh_key_addition

    - name: Ensure correct permissions on authorized_keys file
      file:
        path: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ group }}"
        mode: '0600'
      when: ssh_key_addition is changed

    - name: Allow Ansible user to run sudo without a password
      lineinfile:
        path: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        validate: '/usr/sbin/visudo -cf %s'
      when: user_creation is changed

    - name: Ensure SSH service is running
      service:
        name: sshd
        state: started
        enabled: yes
